language: bash

sudo: false # Use container-based Travis infrastructure

services:
  - mysql
  - postgresql

before_script:
  - mysql -e "CREATE DATABASE dogfish_test;"
  - createdb travis
  - createdb dogfish_test
  - touch .dogfish-test-warning-given

script: ./dogfish_test
