version: "3.5"

networks:
  pydio:
  pydio-private:

volumes:
  pydio-config:
  pydio-data:
  pydio-db:

secrets:
  pydio_admin_password:
    name: ${STACK_NAME:-technocore}_pydio_admin_password
    external: true
  pydio_pydio-db_password:
    name: ${STACK_NAME:-technocore}_pydio_pydio-db_password
    external: true

services:
  # Uncomment this if Traefik will be used for routing traffick to this service.
  ingress:
    networks:
      - pydio

  pydio:
    deploy:
      labels:
        - traefik.frontend.rule=$PYDIO_ROUTING_LABEL
        - traefik.frontend.priority=$PYDIO_ROUTING_LABEL_PRIORITY
        - traefik.port=80
        - ${TRAEFIK_BASIC_AUTH}
        - traefik.enable=true
        - traefik.tags=ingress 
        - traefik.docker.network=${STACK_NAME:-technocore}_pydio
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
        - com.ouroboros.enable=true
      mode: global
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
      # Big services will need this modified or removed.
      #resources:
      #  limits:
      #    memory: 128M
      #  reservations:
      #    memory: 64M
    environment:
      # Sometimes you have to pass in ${DOMAIN} to enable the correct link paths to be generated.
      # Othertimes you can use http:// or https:// for the website. Weird trick.
      - ADMIN_USER=${ADMIN_USER}
      - TZ=${TZ}
    # Might not be needed?
    #hostname: pydio
    image: linuxserver/pydio:latest
    #image: ${image_provider:-scififarms}/technocore-pydio:${TAG:-latest}
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    networks:
      - pydio
      - pydio-private
    secrets:
      - source: pydio_pydio_db_password
        target: pydio_db_password
    volumes:
      - pydio-config:/config
      - pydio-data:/data
      - ${DEV_MOUNT_PYDIO_SHELL_MIGRATIONS:-$EMPTY_MOUNT}

  pydio_db:
    deploy:
      labels:
        - com.ouroboros.enable=true
      mode: global
      restart_policy:
        condition: any
    environment:
      - MYSQL_DATABASE=pydio
      - MYSQL_USER=pydio
      - MYSQL_ROOT_PASSWORD={{"{{DOCKER-SECRET:admin_password}}"}}
      - MYSQL_PASSWORD={{"{{DOCKER-SECRET:pydio_password}}"}}
    image: ${image_provider:-scififarms}/technocore-nextcloud-db:${TAG:-latest}
    #image: mariadb:latest
    #image: ${image_provider:-scififarms}/technocore-pydio-db:${TAG:-latest}
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    networks:
      - pydio-private
    secrets:
      - source: pydio_db_admin_password
        target: admin_password
      - source: pydio_db_pydio_password
        target: pydio_password
    volumes:
      # Likely need to change this
      - pydio-db:/var/lib/mysql
